version: "3.7"
  
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beatrizgameiro_web
    command: /start
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=beatrizgameiro
      - POSTGRES_USER=beatrizgameiro
      - POSTGRES_PASSWORD=beatrizgameiro

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
