version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    image: beatrizgameiro
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - frontend

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=beatrizgameiro
      - POSTGRES_USER=beatrizgameiro
      - POSTGRES_PASSWORD=beatrizgameiro

  frontend:
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
    image: beatrizgameiro_frontend
    command: npm run watch
    volumes:
      - .:/app
      - /app/frontend/node_modules

volumes:
  postgres_data: