version: "3.7"
  
services:

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    container_name: nginx
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email tiagolimadv@gmail.com --agree-tos --no-eff-email --staging -d beatrizgameiro.psc.br -d www.beatrizgameiro.psc.br

  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beatrizgameiro_web
    command: /start
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=beatrizgameiro
      - POSTGRES_USER=beatrizgameiro
      - POSTGRES_PASSWORD=beatrizgameiro
    networks:
      - app-network

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network: